#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

setopt no_global_rcs

export EDITOR=vim
export GIT_EDITOR=$EDITOR
export GEM_HOME="$HOME/.gem"
export PATH="node_modules/.bin:$HOME/.gem/bin:$HOME/go/bin:/usr/local/go/bin:$HOME/Android/Sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export GOPATH="$HOME/go"

[ -s "$HOME/.myenv" ] && source "$HOME/.myenv"

