#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [ -s "$HOME/.bin/tmuxinator.zsh" ]; then
  source ~/.bin/tmuxinator.zsh
fi

if command -v direnv 2>&1 > /dev/null; then
  eval "$(direnv hook zsh)"
fi

if command -v mkcert 2>&1 > /dev/null; then
  export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
fi

function gmain () {
  git show-ref --quiet refs/remotes/origin/master && echo "master" || echo "main"
}

function gdev () {
  git show-ref --quiet refs/remotes/origin/dev && echo "dev" || echo "develop"
}

function gcom () {
  git checkout `gmain`
}

function gcod () {
  git checkout `gdev`
}

function grom () {
  gr origin/`gmain`
}

function grod () {
  gr origin/`gdev`
}

function griom () {
  gr --interactive origin/`gmain`
}

function griod () {
  gr --interactive origin/`gdev`
}

alias rethinkdb='docker run --rm -it -v "`pwd`:/data" --net host rethinkdb'
alias zsource="source $HOME/.zshrc"
alias zvim="vim $HOME/.zshrc"
alias ...="cd ../.."
alias ....="cd ../../.."
alias gro="gr origin"
alias grio="gr --interactive origin"
alias gfcom="gf && gcom"
alias gfrom="gf && grom"
alias gfriom="gf && griom"
alias gfco="git fetch && git checkout"
alias gfcod="gf && gcod"
alias gfrod="gf && grod"
alias gfriod="gf && griod"
alias gu="git pull"
alias gur="git pull --rebase"
alias gph="git push -u origin HEAD"
alias gU="git reset --hard @{upstream}"
alias gfU="git fetch && git reset --hard @{upstream}"
alias glot="git log --date=iso-local --topo-order --pretty=tformat:'%cd %h %s' --abbrev-commit"
alias hush="grep --line-buffered -v"
alias visdom="cd ~/dev/@visdom/flowfront-main"
alias kurr="cd ~/dev/@aboviq/kurr"
alias headcount="cd ~/dev/@visdom/hcfront"
alias itux="docker compose -f ~/dev/@itux/docker-compose.yml"

function icode () {
  code ~/dev/@itux/$1
}

function dreload () {
  docker-compose build --force --no-cache $1 \
  && docker-compose stop $1 \
  && docker-compose rm -f $1 \
  && docker-compose up -d $1
}

function dhick () {
  docker exec -it $(docker ps | grep "$@""[: ]" | awk '{print $1}') sh -c  "ps | grep 'node .*hickup ' | grep -v grep | awk '{print \$1}' | xargs kill -s SIGHUP"
}

function dlog () {
  docker logs ${@:2} $(docker ps | grep "$1""[: ]" | awk '{print $1}')
}

function kublog () {
  kubectl logs -f --since=10m "deployment/${1}" --all-pods | sed 's/^[^[:space:]]*[[:space:]]//' | pino-pretty
}

function git-fix-author () {
	git rebase -i $1 -x "git commit --amend --author '$(git config user.name) <$(git config user.email)>' -CHEAD"
}

if type lt | grep -Fq alias; then
	unalias lt
fi
nocorrects=('compose' 'init' 'aws' 'json' 'jest' 'yarn' 'tsc' 'esbuild' 'ni' 'turbo')

for cmd in $nocorrects; do
  if ! type $cmd | grep -Fq alias; then
    alias $cmd="nocorrect $cmd"
  fi
done


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" || true  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" || true  # This loads nvm bash_completion

autoload -U add-zsh-hook

load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

if command -v nvm 2>&1 > /dev/null; then
  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi

  
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# Scaleway CLI autocomplete initialization.
if command -v scw 2>&1 > /dev/null; then
  eval "$(scw autocomplete script shell=zsh)"
fi


# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/dev/google-cloud-sdk/path.zsh.inc' ]; then . '~/dev/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/dev/google-cloud-sdk/completion.zsh.inc' ]; then . '~/dev/google-cloud-sdk/completion.zsh.inc'; fi

source ~/.docker/init-zsh.sh || true # Added by Docker Desktop

# bun completions
[ -s "~/.bun/_bun" ] && source "~/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# postgres tools
export PATH="/opt/homebrew/opt/postgresql@17/bin:/opt/homebrew/opt/libpq/bin:$PATH"

# Load Angular CLI autocompletion.
# source <(ng completion script)

# pnpm
export PNPM_HOME="~/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# export VOLTA_FEATURE_PNPM=1

if command -v brew 2>&1 > /dev/null; then
  export PATH="$(brew --prefix python)/libexec/bin:$PATH"
fi

export DO_NOT_TRACK=1

